### ISSUE TITLE
Bild failed: some test failing

### ISSUE THREAD

**Issue by stokito** [alphazero/Blake2b#2]
master branch
```
Failed tests:   testFullUpdate(ove.crypto.digest.TestDigest_KAT_DefaultParams): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testSingleByteUpdates(ove.crypto.digest.TestDigest_KAT_DefaultParams): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testFullUpdate(ove.crypto.digest.TestDigest_KAT_ExplicitDefaultParams): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testSingleByteUpdates(ove.crypto.digest.TestDigest_KAT_ExplicitDefaultParams): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testFullUpdate(ove.crypto.digest.TestDigest_KAT_ImplicitDefaultParams): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testSingleByteUpdates(ove.crypto.digest.TestDigest_KAT_ImplicitDefaultParams): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testFullUpdate(ove.crypto.digest.TestMAC_KeyedKAT_DefaultParam): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
  testSingleByteUpdates(ove.crypto.digest.TestMAC_KeyedKAT_DefaultParam): arrays don't have the same size. does not match reference KAT expected:<60928> but was:<58368>
``

**Comment by alphazero** [comment]
Interesting. Your setup specifics? Java version (vendor as well), OS.

**Comment by alphazero** [comment]
Just ran this:

`Results :

Tests run: 25, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:26.137s
[INFO] Finished at: Tue Mar 15 18:49:36 EDT 2016
[INFO] Final Memory: 13M/61M
[INFO] ------------------------------------------------------------------------
ove:Blake2b alphazero$`

**Comment by stokito** [comment]
I found the reason: on my Windows mashine the line endings of blake2b-kat.h, blake2b-kat.out, blake2b-key-kat.out, blake2b-keyed-kat.out files was `CRLF` instead of expected Unix style `LF`.

**Comment by alphazero** [comment]
Knew it had something to do with Windows :) I haven't touched Windows in ages. I'll accept a PR that includes a (new) window's friendly file & mvn profile magic to make it work on that OS. I am just not setup to that on my end. 

Thank you for the report.
